version: '3.8'

services:
  query-agent:
    build:
      context: .
      dockerfile: knowledgebase/query_agent/Dockerfile
    env_file: .env
    networks:
      - agent-network
    ports:
      - "8045:8045"
    volumes:
      - query_agent_data:/app/course_files
      - query_agent_index:/app/faiss_index

  analyzer-agent:
    build:
      context: .
      dockerfile: agents/analyzer_agent/Dockerfile
    env_file: .env
    networks:
      - agent-network
    ports:
      - "8040:8040"

  problem-solver-agent:
    build:
      context: .
      dockerfile: agents/problem_solver_agent/Dockerfile
    env_file: .env
    networks:
      - agent-network
    ports:
      - "8042:8042"

  respondent-agent:
    build:
      context: .
      dockerfile: agents/respondent_agent/Dockerfile
    env_file: .env
    networks:
      - agent-network
    ports:
      - "8043:8043"

  visualization-agent:
    build:
      context: .
      dockerfile: agents/tools/visualization_agent/Dockerfile
    env_file: .env
    networks:
      - agent-network
    ports:
      - "8044:8044"

  canvas-agent:
    build:
      context: .
      dockerfile: agents/canvas_agent/Dockerfile
    image: study_assistant-canvas-agent
    env_file: .env
    depends_on:
      - query-agent
      - analyzer-agent
      - problem-solver-agent
      - respondent-agent
      - visualization-agent
    networks:
      - agent-network
    ports:
      - "8041:8041"

networks:
  agent-network:
    driver: bridge

volumes:
  query_agent_data:
  query_agent_index:
